export const tags = [
  "‌",
  "‌‌",
  "‌‌‌",
  "‌‌‌‌",
  "‌‌‌‌‌",
  "‌‌‌‌‌‌‌",
  "‌‌‌‌‌‌‌‌",
  "‌‌‌‌‌‌‌‌‌‌‌",
  "‌‌‌‌‌‌",
  "‌‌‌‌‌‌‌‌‌‌",
  "HuManIty",
  "Hu‌Man‌Ity",
  "Gandhi",
  "HITLER",
  "SIDA",
  "BlackLivesMatter",
  "Black‌Lives‌Matter",
  "test",
  "dragons",
  "butt",
];

export const user = {
  email: "jake@jake.jake",
  token: "jwt.token.here",
  username: "jake",
  bio: "I work at statefarm",
  image: null,
};

export const comments = {
  comments: [
    {
      id: 103512,
      createdAt: "2021-07-29T18:47:40.214Z",
      updatedAt: "2021-07-29T18:47:40.214Z",
      body: "test",
      author: {
        username: "joe",
        bio: "testing new bio",
        image:
          "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8\u0026ixlib=rb-1.2.1\u0026auto=format\u0026fit=crop\u0026w=800\u0026q=80",
        following: false,
      },
    },
  ],
};

export const articles = {
  articles: [
    {
      title: "fghd",
      slug: "fghd-fhqzxt",
      body: "# hi\ncool",
      createdAt: "2021-07-18T09:24:49.853Z",
      updatedAt: "2021-07-18T09:24:49.853Z",
      tagList: ["hi"],
      description: "fghdgf",
      author: {
        username: "Samuel Hart",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "My first article",
      slug: "my-first-article-uiz9mt",
      body: "This is the best course about Angular",
      createdAt: "2021-07-18T09:20:13.306Z",
      updatedAt: "2021-07-18T09:20:13.306Z",
      tagList: [],
      description: "About test",
      author: {
        username: "Alexsoft",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "title",
      slug: "title-kejr8n",
      body: "hello world",
      createdAt: "2021-07-18T09:09:13.917Z",
      updatedAt: "2021-07-18T09:09:13.917Z",
      tagList: [],
      description: "testing",
      author: {
        username: "joe",
        bio: "testing new bio",
        image:
          "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8\u0026ixlib=rb-1.2.1\u0026auto=format\u0026fit=crop\u0026w=800\u0026q=80",
        following: false,
      },

      favorited: false,
      favoritesCount: 2,
    },
    {
      title: "sgrgrgr",
      slug: "sgrgrgr-8uir5i",
      body: "rgrgrgrgr",
      createdAt: "2021-07-18T08:54:14.220Z",
      updatedAt: "2021-07-18T08:54:14.220Z",
      tagList: [],
      description: "grgrgrg",
      author: {
        username: "Commodo in mollitia ",
        bio: "1",
        image: "",
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: "This is a title",
      slug: "this-is-a-title-5me0a7",
      body: "This is a body of article",
      createdAt: "2021-07-18T08:26:41.892Z",
      updatedAt: "2021-07-18T08:26:41.892Z",
      tagList: [],
      description: "This is a description",
      author: {
        username: "Khan",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: "This is a title",
      slug: "this-is-a-title-t09g6b",
      body: "This is a body of article",
      createdAt: "2021-07-18T08:24:57.658Z",
      updatedAt: "2021-07-18T08:24:57.658Z",
      tagList: [],
      description: "This is a description",
      author: {
        username: "Khan",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "This is a title",
      slug: "this-is-a-title-qeaxt5",
      body: "This is a body of article",
      createdAt: "2021-07-18T08:20:26.150Z",
      updatedAt: "2021-07-18T08:20:26.150Z",
      tagList: [],
      description: "This is a description",
      author: {
        username: "Khan",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: "This is a title",
      slug: "this-is-a-title-n9eshz",
      body: "This is a body of article",
      createdAt: "2021-07-18T07:59:20.928Z",
      updatedAt: "2021-07-18T07:59:20.928Z",
      tagList: [],
      description: "This is a description",
      author: {
        username: "Khan",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: "Andamina Boma",
      slug: "andamina-boma-ueq8lf",
      body: "some experiences",
      createdAt: "2021-07-18T07:03:05.656Z",
      updatedAt: "2021-07-18T07:03:05.656Z",
      tagList: [],
      description: "Bla Bla",
      author: {
        username: "Zera",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "Andamina Boma",
      slug: "andamina-boma-71haj8",
      body: "some experiences",
      createdAt: "2021-07-18T06:58:28.263Z",
      updatedAt: "2021-07-18T06:58:28.263Z",
      tagList: [],
      description: "Bla Bla",
      author: {
        username: "Zera",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "Andamina Boma",
      slug: "andamina-boma-513jwk",
      body: "some experiences",
      createdAt: "2021-07-18T06:54:17.063Z",
      updatedAt: "2021-07-18T06:54:17.063Z",
      tagList: [],
      description: "Bla Bla",
      author: {
        username: "Zera",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "sd",
      slug: "sd-qgh69m",
      body: "sd",
      createdAt: "2021-07-18T06:46:41.736Z",
      updatedAt: "2021-07-18T06:46:41.736Z",
      tagList: [],
      description: "sd",
      author: {
        username: "qwertyui@hjkl.ri",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "wew",
      slug: "wew-kbxxsh",
      body: "we",
      createdAt: "2021-07-18T06:27:54.080Z",
      updatedAt: "2021-07-18T06:27:54.080Z",
      tagList: [],
      description: "wew",
      author: {
        username: "user404",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "teste",
      slug: "teste-7ypgql",
      body: "teste",
      createdAt: "2021-07-18T05:53:02.396Z",
      updatedAt: "2021-07-18T05:53:02.396Z",
      tagList: [],
      description: "teste",
      author: {
        username: "Grupo Primo",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "Testing",
      slug: "testing-gx3lci",
      body: "Testing",
      createdAt: "2021-07-18T05:16:46.120Z",
      updatedAt: "2021-07-18T05:16:46.120Z",
      tagList: [],
      description: "Testing",
      author: {
        username: "KarateTest09",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "Test",
      slug: "test-zsf4zg",
      body: "Test for API",
      createdAt: "2021-07-18T05:02:52.281Z",
      updatedAt: "2021-07-18T05:02:52.281Z",
      tagList: [],
      description: "Try me ",
      author: {
        username: "KarateTest09",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "Grupo Primo",
      slug: "grupo-primo-d3xnjk",
      body: "Follow @thiago.nigro on Instagram",
      createdAt: "2021-07-18T04:06:44.255Z",
      updatedAt: "2021-07-18T04:06:44.255Z",
      tagList: [],
      description: "Best investment and entrepreneur content",
      author: {
        username: "Grupo Primo",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "Grupo Primo",
      slug: "grupo-primo-khscyb",
      body: "Follow @thiago.nigro on Instagram",
      createdAt: "2021-07-18T04:04:49.192Z",
      updatedAt: "2021-07-18T04:04:49.192Z",
      tagList: [],
      description: "Best investment and entrepreneur content",
      author: {
        username: "Grupo Primo",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "Grupo Primo",
      slug: "grupo-primo-i9w7o8",
      body: "Follow @thiago.nigro on Instagram",
      createdAt: "2021-07-18T04:04:21.943Z",
      updatedAt: "2021-07-18T04:04:21.943Z",
      tagList: [],
      description: "Best investment and entrepreneur content",
      author: {
        username: "Grupo Primo",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: "Grupo Primo",
      slug: "grupo-primo-pzp1yi",
      body: "Follow @thiago.nigro on Instagram",
      createdAt: "2021-07-18T03:55:15.295Z",
      updatedAt: "2021-07-18T03:55:15.295Z",
      tagList: [],
      description: "Best investment and entrepreneur content",
      author: {
        username: "Grupo Primo",
        bio: null,
        image: "https://static.productionready.io/images/smiley-cyrus.jpg",
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
  ],
  articlesCount: 500,
};
